highlighter: pygments
github: [Repository metadata]

defaults:
  -
    scope:
      path: "_posts/"
      type: "posts"
    values:
      layout: "posts"

port: 4444

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
