highlighter: pygments
github: [Repository metadata]

name: "jgarofoli@github's notes"
description: "mostly notes to keep handy"
url: http://jgarofoli.github.io

defaults:
  -
    scope:
      path: ""
    values:
      author: "jgarofoli"
      shownav: false
      includemath: false # set to true when including math
  -
    scope:
      path: "" # don't put "_posts/" here
      type: "posts"
    values:
      layout: "post"
      shownav: true
  -
    scope:
      path: "" # don't put "_posts/" here
      type: "drafts"
    values:
      layout: "post"
      shownav: true

port: 4444

redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
