highlighter: pygments
github: [Repository metadata]

defaults:
  -
    scope:
      path: ""
    values:
      author: "jgarofoli"
      shownav: false
      includemath: false # set to true when including math
  -
    scope:
      path: "" # don't put "_posts/" here
      type: "posts"
    values:
      layout: "post"
      shownav: true
  -
    scope:
      path: "" # don't put "_posts/" here
      type: "drafts"
    values:
      layout: "post"
      shownav: true

port: 4444

markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
